/**
 * Per-glyph advance widths for tldraw's four fonts (draw, sans, serif,
 * mono), regenerated by `tools/font-metrics.mts` at the default size (`m`,
 * 22px): each printable ASCII character rendered 20 times and divided
 * (space measured by differencing `"a a a ... a"` against `"aaaa..."`).
 * Glyph advance scales exactly linearly with font size (measured across all
 * 16 (font, size) combinations, max error 0.001px predicting a target size
 * from the size-`m` table times `LABEL_FONT_PX[size] / BASE_FONT_PX`), so
 * only one table per font is stored; `textWidth` applies the size scale.
 */

import type { StyleFont, StyleFontSize } from "../ir/styles.js";

/**
 * Kept exactly as first measured, so every geometry baseline still reproduces.
 * A re-measurement disagrees on two glyphs only - `" "` (7.62) and `"#"`
 * (21.63) - both under-reserved here and both inside `TEXT_SLACK_PX`. Do not
 * "correct" them without re-rendering the corpus.
 */
const DRAW_ADVANCE: Record<string, number> = {
  " ": 7.15, "!": 6.41, "\"": 10.89, "#": 21.40, "$": 14.94, "%": 21.14,
  "&": 14.74, "'": 5.78, "(": 10.43, ")": 8.65, "*": 11.15, "+": 15.40,
  ",": 6.32, "-": 11.18, ".": 5.98, "/": 7.51, "0": 15.14, "1": 8.99,
  "2": 15.19, "3": 15.00, "4": 15.90, "5": 13.54, "6": 15.53, "7": 14.40,
  "8": 15.15, "9": 14.96, ":": 6.62, ";": 6.75, "<": 15.40, "=": 15.40,
  ">": 15.40, "?": 11.24, "@": 19.69, "A": 16.59, "B": 13.74, "C": 13.06,
  "D": 14.97, "E": 14.60, "F": 13.05, "G": 17.66, "H": 15.92, "I": 13.77,
  "J": 13.97, "K": 14.84, "L": 11.25, "M": 21.25, "N": 16.91, "O": 15.48,
  "P": 13.19, "Q": 17.59, "R": 16.85, "S": 12.30, "T": 13.91, "U": 14.69,
  "V": 15.53, "W": 21.14, "X": 14.10, "Y": 13.87, "Z": 14.02, "[": 11.17,
  "\\": 8.98, "]": 10.97, "^": 13.42, "_": 15.40, "`": 7.79, "a": 14.61,
  "b": 13.17, "c": 10.90, "d": 14.57, "e": 13.22, "f": 10.43, "g": 14.46,
  "h": 14.88, "i": 6.73, "j": 7.45, "k": 13.58, "l": 7.73, "m": 19.69,
  "n": 14.37, "o": 13.52, "p": 13.13, "q": 13.76, "r": 10.99, "s": 11.50,
  "t": 10.57, "u": 13.47, "v": 13.13, "w": 20.85, "x": 12.83, "y": 13.16,
  "z": 13.41, "{": 11.84, "|": 7.04, "}": 11.84, "~": 15.40,
};

const SANS_ADVANCE: Record<string, number> = {
  " ": 5.19, "!": 6.56, "\"": 9.92, "#": 14.92, "$": 13.18, "%": 20.83,
  "&": 15.55, "'": 5.57, "(": 7.39, ")": 7.39, "*": 11.31, "+": 13.20,
  ",": 6.38, "-": 8.82, ".": 6.38, "/": 6.04, "0": 13.20, "1": 13.20,
  "2": 13.20, "3": 13.20, "4": 13.20, "5": 13.20, "6": 13.20, "7": 13.20,
  "8": 13.20, "9": 13.20, ":": 6.82, ";": 6.82, "<": 13.20, "=": 13.20,
  ">": 13.20, "?": 10.71, "@": 19.71, "A": 14.84, "B": 14.50, "C": 13.68,
  "D": 15.03, "E": 13.05, "F": 12.54, "G": 15.51, "H": 15.71, "I": 9.15,
  "J": 11.49, "K": 14.52, "L": 11.29, "M": 17.91, "N": 15.71, "O": 15.66,
  "P": 13.79, "Q": 15.66, "R": 14.41, "S": 12.91, "T": 13.11, "U": 15.09,
  "V": 13.92, "W": 20.46, "X": 14.06, "Y": 13.57, "Z": 13.00, "[": 7.15,
  "\\": 9.17, "]": 7.15, "^": 13.20, "_": 12.34, "`": 13.20, "a": 12.08,
  "b": 13.02, "c": 11.10, "d": 13.02, "e": 12.23, "f": 7.52, "g": 11.90,
  "h": 12.76, "i": 5.83, "j": 5.83, "k": 12.03, "l": 6.15, "m": 19.40,
  "n": 12.76, "o": 12.41, "p": 13.02, "q": 13.02, "r": 8.43, "s": 10.74,
  "t": 7.88, "u": 12.76, "v": 11.26, "w": 17.58, "x": 11.66, "y": 11.31,
  "z": 10.71, "{": 7.79, "|": 7.77, "}": 7.83, "~": 13.20,
};

const SERIF_ADVANCE: Record<string, number> = {
  " ": 5.10, "!": 6.42, "\"": 9.77, "#": 14.76, "$": 13.05, "%": 20.22,
  "&": 15.97, "'": 5.48, "(": 7.39, ")": 7.39, "*": 11.13, "+": 13.20,
  ",": 5.98, "-": 8.71, ".": 5.98, "/": 6.12, "0": 13.20, "1": 13.20,
  "2": 13.20, "3": 13.20, "4": 13.20, "5": 13.20, "6": 13.20, "7": 13.20,
  "8": 13.20, "9": 13.20, ":": 6.42, ";": 6.45, "<": 13.20, "=": 13.20,
  ">": 13.20, "?": 11.02, "@": 20.11, "A": 15.54, "B": 15.07, "C": 14.16,
  "D": 16.02, "E": 14.28, "F": 13.90, "G": 16.70, "H": 17.58, "I": 7.99,
  "J": 9.79, "K": 16.17, "L": 13.33, "M": 19.40, "N": 17.25, "O": 16.32,
  "P": 14.30, "Q": 16.32, "R": 15.38, "S": 13.16, "T": 15.35, "U": 16.50,
  "V": 15.10, "W": 22.06, "X": 15.27, "Y": 14.41, "Z": 13.96, "[": 6.80,
  "\\": 8.62, "]": 6.80, "^": 13.20, "_": 12.39, "`": 13.20, "a": 12.17,
  "b": 13.40, "c": 11.36, "d": 13.62, "e": 12.03, "f": 7.92, "g": 12.32,
  "h": 13.97, "i": 7.11, "j": 6.84, "k": 13.13, "l": 6.82, "m": 21.08,
  "n": 14.26, "o": 12.79, "p": 13.68, "q": 13.42, "r": 10.21, "s": 10.81,
  "t": 7.82, "u": 13.88, "v": 12.45, "w": 18.16, "x": 12.63, "y": 12.54,
  "z": 11.24, "{": 7.68, "|": 7.30, "}": 7.68, "~": 13.20,
};

const MONO_ADVANCE: Record<string, number> = {
  " ": 13.20, "!": 13.20, "\"": 13.20, "#": 13.20, "$": 13.20, "%": 13.20,
  "&": 13.20, "'": 13.20, "(": 13.20, ")": 13.20, "*": 13.20, "+": 13.20,
  ",": 13.20, "-": 13.20, ".": 13.20, "/": 13.20, "0": 13.20, "1": 13.20,
  "2": 13.20, "3": 13.20, "4": 13.20, "5": 13.20, "6": 13.20, "7": 13.20,
  "8": 13.20, "9": 13.20, ":": 13.20, ";": 13.20, "<": 13.20, "=": 13.20,
  ">": 13.20, "?": 13.20, "@": 13.20, "A": 13.20, "B": 13.20, "C": 13.20,
  "D": 13.20, "E": 13.20, "F": 13.20, "G": 13.20, "H": 13.20, "I": 13.20,
  "J": 13.20, "K": 13.20, "L": 13.20, "M": 13.20, "N": 13.20, "O": 13.20,
  "P": 13.20, "Q": 13.20, "R": 13.20, "S": 13.20, "T": 13.20, "U": 13.20,
  "V": 13.20, "W": 13.20, "X": 13.20, "Y": 13.20, "Z": 13.20, "[": 13.20,
  "\\": 13.20, "]": 13.20, "^": 13.20, "_": 13.20, "`": 13.20, "a": 13.20,
  "b": 13.20, "c": 13.20, "d": 13.20, "e": 13.20, "f": 13.20, "g": 13.20,
  "h": 13.20, "i": 13.20, "j": 13.20, "k": 13.20, "l": 13.20, "m": 13.20,
  "n": 13.20, "o": 13.20, "p": 13.20, "q": 13.20, "r": 13.20, "s": 13.20,
  "t": 13.20, "u": 13.20, "v": 13.20, "w": 13.20, "x": 13.20, "y": 13.20,
  "z": 13.20, "{": 13.20, "|": 13.20, "}": 13.20, "~": 13.20,
};

/** Exported only so tests can assert every `FONTS`/`FONT_SIZES` enum value has a table. */
export const ADVANCE: Record<StyleFont, Record<string, number>> = {
  draw: DRAW_ADVANCE,
  sans: SANS_ADVANCE,
  serif: SERIF_ADVANCE,
  mono: MONO_ADVANCE,
};

/** Any character not in a font's table (non-ASCII) is over- rather than under-reserved. */
const MAX_ADVANCE: Record<StyleFont, number> = Object.fromEntries(
  Object.entries(ADVANCE).map(([font, table]) => [font, Math.max(...Object.values(table))]),
) as Record<StyleFont, number>;

/** tldraw's `LABEL_FONT_SIZES` - a label drawn *inside* a geo box or note. Exported for the same test-coverage reason as `ADVANCE`. */
export const LABEL_FONT_PX: Record<StyleFontSize, number> = { s: 18, m: 22, l: 26, xl: 32 };
/**
 * tldraw's `FONT_SIZES` - the standalone `text` shape `<Text>` emits
 * (`IRBox.text`), a third table distinct from `LABEL_FONT_PX` the same way
 * `ARROW_LABEL_FONT_PX` is.
 */
export const TEXT_FONT_PX: Record<StyleFontSize, number> = { s: 18, m: 24, l: 36, xl: 44 };
/** Every glyph table above was measured at this size; other sizes scale linearly off it. */
const BASE_FONT_PX = LABEL_FONT_PX.m;

/** Covers the worst measured under-prediction (1.58px, `SystemClock`) plus integer rounding. */
export const TEXT_SLACK_PX = 4;

export interface TextStyle {
  font?: StyleFont;
  size?: StyleFontSize;
  /**
   * True for a standalone tldraw `text` shape (`IRBox.text`, `<Text>`) - sizes
   * off `TEXT_FONT_PX` instead of `LABEL_FONT_PX`. Named `standalone` rather
   * than `text` because `IRNote.text` is string content, not a style flag, and
   * a note is passed here as its own style.
   */
  standalone?: boolean;
}

export const DEFAULT_FONT: StyleFont = "draw";
export const DEFAULT_FONT_SIZE: StyleFontSize = "m";

function fontPxTable(ts?: TextStyle): Record<StyleFontSize, number> {
  return ts?.standalone ? TEXT_FONT_PX : LABEL_FONT_PX;
}

/** `fontPxTable(ts)[size] / BASE_FONT_PX` - the linear scale a size applies over the size-`m` tables. */
export function fontScale(ts?: TextStyle): number {
  return fontPxTable(ts)[ts?.size ?? DEFAULT_FONT_SIZE] / BASE_FONT_PX;
}

function rawAdvance(s: string, font: StyleFont): number {
  const table = ADVANCE[font];
  let w = 0;
  for (const ch of s) w += table[ch] ?? MAX_ADVANCE[font];
  return w;
}

export function textWidth(s: string, ts?: TextStyle): number {
  if (s.length === 0) return 0;
  const font = ts?.font ?? DEFAULT_FONT;
  return rawAdvance(s, font) * fontScale(ts) + TEXT_SLACK_PX;
}

/** tldraw's `TEXT_PROPS.lineHeight` is 1.35x the font size; rounded up for integer geometry. */
export function lineHeightPx(ts?: TextStyle): number {
  return Math.ceil(fontPxTable(ts)[ts?.size ?? DEFAULT_FONT_SIZE] * 1.35);
}

/** tldraw's `ARROW_LABEL_FONT_SIZES` - distinct from `LABEL_FONT_PX`, which is box/note only. */
export const ARROW_LABEL_FONT_PX: Record<StyleFontSize, number> = { s: 18, m: 20, l: 24, xl: 28 };

/** tldraw's `ARROW_LABEL_PADDING`, added on every side of the label box. */
export const ARROW_LABEL_PADDING = 4.25;

/** Same measurement as `textWidth`, scaled by the arrow label's own font-size table instead of `LABEL_FONT_PX`. */
export function arrowLabelWidth(s: string, ts?: TextStyle): number {
  if (s.length === 0) return 0;
  const font = ts?.font ?? DEFAULT_FONT;
  const scale = ARROW_LABEL_FONT_PX[ts?.size ?? DEFAULT_FONT_SIZE] / BASE_FONT_PX;
  return rawAdvance(s, font) * scale + TEXT_SLACK_PX;
}

/** tldraw's `TEXT_PROPS.lineHeight` (1.35x) applied to the arrow label's own font-size table. */
export function arrowLabelLineHeight(ts?: TextStyle): number {
  return ARROW_LABEL_FONT_PX[ts?.size ?? DEFAULT_FONT_SIZE] * 1.35;
}
